site_name: Weave
site_url: https://andrewtdiz.github.com/Weave
repo_name: andrewtdiz/Weave
repo_url: https://github.com/andrewtdiz/Weave

extra:
  version:
    provider: mike

theme:
  name: material
  custom_dir: docs/assets/overrides
  logo: assets/logo
  favicon: assets/logo.svg
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: weavedoc-dark
      toggle:
        icon: octicons/sun-24
        title: Switch to light theme
    - media: "(prefers-color-scheme: light)"
      scheme: weavedoc-light
      toggle:
        icon: octicons/moon-24
        title: Switch to dark theme
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight
  icon:
    repo: octicons/mark-github-16

extra_css:
  - assets/theme/weavedoc.css
  - assets/theme/colours.css
  - assets/theme/code.css
  - assets/theme/paragraph.css
  - assets/theme/page.css
  - assets/theme/admonition.css
  - assets/theme/404.css
  - assets/theme/api-reference.css

extra_javascript:
  - assets/scripts/smooth-scroll.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Weave:
      - Why Weave?: tutorials/index.md
      - Installation: tutorials/installation/index.md
      - Getting Started: tutorials/started/index.md
      - State Objects:
          - Value: tutorials/fundamentals/values.md
          - Computed: tutorials/fundamentals/computeds.md
      - Instances:
          - Attach: tutorials/instances/attach.md
      - Networking:
          - Networking: tutorials/networking/networking.md
          - NetworkValue: tutorials/networking/networkvalue.md
          - PlayerValue: tutorials/networking/playervalue.md
          - ProfileValue: tutorials/networking/profilevalue.md
          - ProfilePlayerValue: tutorials/networking/profileplayervalue.md
      - Summary:
          - Conclusion: tutorials/conclusion/index.md
  # - API:
  #   - Instances:
  #       - Attribute Value: tutorials/instances/attributevalue.md
  #       - New Instances: tutorials/instances/new-instances.md
  #   - Components:
  #       - Reusing UI: tutorials/components/reusing-ui.md  
  - UI:
    - Lists & Tables:
        - The For Objects: tutorials/lists-and-tables/the-for-objects.md
        - ForValues: tutorials/lists-and-tables/forvalues.md
        - ForKeys: tutorials/lists-and-tables/forkeys.md
        - ForPairs: tutorials/lists-and-tables/forpairs.md
    # - Instances:
    #     - Children: tutorials/instances/parenting.md
    #     - Cleanup: tutorials/instances/cleanup.md
    #     - Destructors: tutorials/fundamentals/destructors.md
    - Animation:
        - Tweens: tutorials/animation/tweens.md
        - Springs: tutorials/animation/springs.md
  - Advanced:
    - Instances:
        - Attribute Value: tutorials/instances/attributevalue.md
        # - New Instances: tutorials/instances/new-instances.md
    - Components:
        - Reusing UI: tutorials/components/reusing-ui.md
  # - Examples:
  #     - Home: examples/index.md
  #     - Cookbook:
  #         - examples/cookbook/index.md
  #         - Player List: examples/cookbook/player-list.md
  #         - Animated Computed: examples/cookbook/animated-computed.md
  #         - Fetch Data From Server: examples/cookbook/fetch-data-from-server.md
  #         - Light & Dark Theme: examples/cookbook/light-and-dark-theme.md
  #         - Button Component: examples/cookbook/button-component.md
  #         - Loading Spinner: examples/cookbook/loading-spinner.md
  #         - Drag & Drop: examples/cookbook/drag-and-drop.md
  # - API Reference:
  #     - Home: api-reference/index.md
  #     - Errors:
  #         - api-reference/errors/index.md
  #     - State:
  #         - api-reference/state/index.md
  #         - CanBeState: api-reference/state/canbestate.md
  #         - Computed: api-reference/state/computed.md
  #         - cleanup: api-reference/state/cleanup.md
  #         - Dependency: api-reference/state/dependency.md
  #         - Dependent: api-reference/state/dependent.md
  #         - doNothing: api-reference/state/doNothing.md
  #         - ForKeys: api-reference/state/forkeys.md
  #         - ForPairs: api-reference/state/forpairs.md
  #         - ForValues: api-reference/state/forvalues.md
  #         - Observer: api-reference/state/observer.md
  #         - StateObject: api-reference/state/stateobject.md
  #         - Value: api-reference/state/value.md
  #     - Instances:
  #         - api-reference/instances/index.md
  #         - Child: api-reference/instances/child.md
  #         - Children: api-reference/instances/children.md
  #         - Cleanup: api-reference/instances/cleanup.md
  #         - Component: api-reference/instances/component.md
  #         - Hydrate: api-reference/instances/hydrate.md
  #         - New: api-reference/instances/new.md
  #         - OnChange: api-reference/instances/onchange.md
  #         - OnEvent: api-reference/instances/onevent.md
  #         - Out: api-reference/instances/out.md
  #         - Ref: api-reference/instances/ref.md
  #         - SpecialKey: api-reference/instances/specialkey.md
  #     - Animation:
  #         - api-reference/animation/index.md
  #         - Animatable: api-reference/animation/animatable.md
  #         - Tween: api-reference/animation/tween.md
  #         - Spring: api-reference/animation/spring.md

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - md_in_html
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: false
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
