[package]
name = "andrewtdiz/weave"
description = "Weave is a state management and networking library for insanely fast Roblox development."
license = "MIT"
authors = ["andrewtdiz"]
version = "0.1.3"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
